spring.application.name=nim-rest-client

# Dev 8080, Prod 80 ... -> Spring Profiles
# Render -> 10000
server.port=${PORT:8080}

# mvc prefix, suffix -> /WEB-INF/views/ .jsp
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp